
source "https://rubygems.org"
gem 'bcrypt'
gem 'sinatra'
gem 'sinatra-jsonp'
gem "sqlite3"
gem "activerecord"
gem "sinatra-activerecord"
gem "sinatra-cross_origin", "~> 0.3.1"
group :development do 
	gem 'shotgun'
	gem 'tux'
end